---
# Elasticsearch Ansible Tasks

# Install Java
- include: java.yml
  when: elasticsearch_install_java

# Configure timezome
- include: timezone.yml

# Install and configure elasticsearch
- include: elastic-install.yml

# Install AWS Plugin
- include: aws.yml
  when: (elasticsearch_plugin_aws_version is defined)

# Install Other Generic Plugins
- include: plugins.yml
  when: (elasticsearch_plugins is defined)

# Install custom JARs
- include: custom-jars.yml
  when: (elasticsearch_custom_jars is defined)

# restore elasticsearch snapshot
- name: restore elasticsearch snapshot
  include: es_restore.yml
  tags: elasticsearch_restore
  when: elasticsearch_snapshot_restore_name is defined

# create  elasticsearch snapshot
- name: restore elasticsearch snapshot
  include: es_snapshot.yml
  tags: elasticsearch_snapshot
  when: elasticsearch_snapshot_name is defined

# Setup Shield
- include: shield.yml
  when: (elasticsearch_shield_enabled is defined and elasticsearch_shield_enabled == "true")

- name: copy in config files
  synchronize: src={{elasticsearch_config_files }} dest=/etc/elasticsearch/ owner=no group=no
  tags: elastic_config_files
  when: (elasticsearch_config_files is defined)
  notify: Restart Elasticsearch

- name: make sure config dir has correct permissions if elasticsearch_config_files
  file: path=/etc/elasticsearch/config/ state=directory mode=0755 recurse=yes owner={{elasticsearch_user}} group={{elasticsearch_group}}
  when: (elasticsearch_config_files is defined)



# Always run post-run tasks
- include: post-run.yml
